apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multitool-ds
spec:
  selector:
    matchLabels:
      app: multitool-ds
  template:
    metadata:
      labels:
        app: multitool-ds
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        securityContext:
          privileged: true
        volumeMounts:
        - name: varlog
          mountPath: /host/var/log
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
          type: Directory
